version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.13-rc-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  db_service:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1434:1433
    volumes:
      - ./mssql/db_service:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=IsFaYhv7iohrUh0
